"""Recreate migration with condition column

Revision ID: 2a12f1fe9b69
Revises: 
Create Date: 2024-12-26 16:37:47.307272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2a12f1fe9b69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=26), nullable=False, server_default='Neuf'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('condition')

    op.create_table('_alembic_tmp_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('main_photo', sa.VARCHAR(length=250), nullable=True),
    sa.Column('photos', sqlite.JSON(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('is_promotion', sa.BOOLEAN(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), nullable=False),
    sa.Column('extra_attributes', sqlite.JSON(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('original_price', sa.FLOAT(), nullable=True),
    sa.Column('is_top_product', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('condition', sa.VARCHAR(length=26), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
